### ISSUE TITLE
Chyba při použití verze 0.3.0

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/thumby#13]
V případě, že mám nainstalovaný thumby==0.3.0 dostávám tuto chybu:
![image](https://github.com/ThunderFly-aerospace/thumby/assets/5196729/07e72fa8-c59c-4d0d-a5ae-a741f05fd502)

Rychlá oprava je návrat na 0.2.3. Pak vkládání obrázků funguje.

**Comment by kaklik** [comment]
Myslíš, že bys to prosím mohl vyřešit @cisar2218 ?  Docela rád bych zavedl do workflow poslední verze.

**Comment by cisar2218** [comment]
Vyřeším do konce týdne.

**Comment by cisar2218** [comment]
Vyřešeno #14. Potvrď prosím, že funguje jak má.

**Comment by kaklik** [comment]
> Vyřešeno #14. Potvrď prosím, že funguje jak má.

Super! Funguje to :) 
Omlouvám se za zpoždění, ale abych to vyzkoušel, tak jsem musel vyřešit několik detailů ve workflow Processor3D. 

Díky.
