### ISSUE TITLE
Náhledy modelů v g-kódech - obrázky na displej tiskárny

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/thumby#6]
Průša MINI tiskárny předpokládají, že součástí g-kódu je base64 náhled tištěného dílu, který se následně zobrazuje uživateli na displeji tiskárny. 
Tento přístup je v různých obměnách relativně standardní a například tiskárna edee jej používá, jen je to skryté za balíčkovacím nástrojem, který ten base64 obrázek do gkódu vloží společně s dalšími informacemi. Viz balíčkování gkódů ThunderFly-aerospace/processor3D#6. 

## Formát náhledů v gkódech
 
![200997454_226680732414900_7432375214069097700_n](https://user-images.githubusercontent.com/1194177/122798612-118e6d80-d2c1-11eb-9152-ea19a738221b.jpg)

@taury55  udělal experiment s tiskárnou Průša MINI +, kde zjistil že. 

- V gcodu jsou 3 thumbnaily (16x16, 220x124, 240x320)
- Když  zkusil změnit velikost, tak to tiskárna ignorovala.
- A počet datových znaků na řádku je nutně 76.

## Obsah obrázků

Samostatným problémem ještě je, jaký obrázek má být v gkódu uložen. Vzhledem k nízkému rozlišení je asi vhodné, aby to byl náhledový obrázek modelu. 
Ten je však generován [odlišným worflow](https://github.com/ThunderFly-aerospace/TF-G2/blob/4s/.github/workflows/render_previews.yml). Pro vyvoření tiskových souborů by pak vznikala závislost mezi jednotlivými worflow, což je nepříjemné jednak z důvodu, že by nebyly zpracovány paralelně a také sekvenční závislost prodlouží potřebný čas zpracování.

Obrázky z gkódů pak naopak neefektivně pracují s nízkým rozlišením. Zvláště pak v případech, kdy není dobře vyřešeno [centrování do zorného pole.](https://github.com/ThunderFly-aerospace/gcodes/issues/3)

**Comment by roman-dvorak** [comment]
> Správně nahrát na PyPI ([aktuálně](https://pypi.org/project/thumby/#description) nahráno, ale zatím nefunguje)

K tomuto bodu by bylo nejlepší, aby se to na pypi nahravalo samo po nějaké zmeně/vytvoření releasu/zmergerování do master větve. 
Nejsnáze to lze pomocí nějakého github actions. Které může vypadat například [takto](https://github.com/MLAB-project/pymlab/blob/master/.github/workflows/python-publish.yml). Kdybys potřeboval, můžu s konfigurací pomoct.

**Comment by cisar2218** [comment]
přidal jsem tedy tento [script (odkaz na dokumentaci)](https://github.com/ThunderFly-aerospace/thumby#cli-script-gcode_img_inserterpy), který jde použít pro vkládání gcodů a odstraňování thumbnailů z gcodů. Na 3d tiskárně jsem to nezkoušel, ale na lokálních souborech to vypadá dobře. Ten script je hodně jednoduchý. Můžu ho rozšířit o nějaké další možnosti případně udělat více fancy (zpracovávání argumentů atd) pokud by to bylo žádoucí. S čím trochu bojuju je, že nevím zda bych měl tento script oddělit jako nějaký modul zvlášť, nebo ho mám nechat ve složce knihovny jak je, či zda je nějaká jiná good practice jak to zařadit v rámci projektu.

**Comment by taury55** [comment]
G-kódy jsem otestoval na Prusa Mini a jsou funkční. Viz obrázky:

**Comment by cisar2218** [comment]
Je současné řešení v podobě [thumby](https://github.com/ThunderFly-aerospace/thumby) dostačující (možno zavřít issue / unassign me)?

**Comment by kaklik** [comment]
> Je současné řešení v podobě [thumby](https://github.com/ThunderFly-aerospace/thumby) dostačující (možno zavřít issue)?

jo je, funguje to parádně! :)
